# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1314, 700)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(610, 300, 291, 31))
        self.label_3.setObjectName("label_3")
        self.results_folder_path = QtWidgets.QLineEdit(self.centralwidget)
        self.results_folder_path.setEnabled(False)
        self.results_folder_path.setGeometry(QtCore.QRect(610, 330, 391, 21))
        self.results_folder_path.setObjectName("results_folder_path")
        self.choose_folder_btn = QtWidgets.QPushButton(self.centralwidget)
        self.choose_folder_btn.setGeometry(QtCore.QRect(1010, 330, 61, 21))
        self.choose_folder_btn.setText("")
        self.choose_folder_btn.setObjectName("choose_folder_btn")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 570, 591, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.info_field = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.info_field.setEnabled(False)
        self.info_field.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.info_field.setReadOnly(True)
        self.info_field.setObjectName("info_field")
        self.verticalLayout.addWidget(self.info_field)
        self.main_graph = PlotWidget(self.centralwidget)
        self.main_graph.setGeometry(QtCore.QRect(10, 70, 591, 491))
        self.main_graph.setObjectName("main_graph")
        self.line_graph = PlotWidget(self.centralwidget)
        self.line_graph.setGeometry(QtCore.QRect(610, 360, 321, 291))
        self.line_graph.setObjectName("line_graph")
        self.gauss_graph = PlotWidget(self.centralwidget)
        self.gauss_graph.setGeometry(QtCore.QRect(950, 360, 341, 291))
        self.gauss_graph.setObjectName("gauss_graph")
        self.translator_coords_graph = PlotWidget(self.centralwidget)
        self.translator_coords_graph.setGeometry(QtCore.QRect(610, 20, 391, 281))
        self.translator_coords_graph.setObjectName("translator_coords_graph")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(1010, 10, 301, 317))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.connect_translator_btn = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connect_translator_btn.sizePolicy().hasHeightForWidth())
        self.connect_translator_btn.setSizePolicy(sizePolicy)
        self.connect_translator_btn.setMinimumSize(QtCore.QSize(0, 24))
        self.connect_translator_btn.setStyleSheet("background-color: rgb(211, 255, 190);")
        self.connect_translator_btn.setObjectName("connect_translator_btn")
        self.gridLayout.addWidget(self.connect_translator_btn, 0, 0, 1, 2)
        self.disconnect_translator_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.disconnect_translator_btn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.disconnect_translator_btn.sizePolicy().hasHeightForWidth())
        self.disconnect_translator_btn.setSizePolicy(sizePolicy)
        self.disconnect_translator_btn.setMinimumSize(QtCore.QSize(0, 24))
        self.disconnect_translator_btn.setStyleSheet("background-color: rgb(255, 205, 205);")
        self.disconnect_translator_btn.setObjectName("disconnect_translator_btn")
        self.gridLayout.addWidget(self.disconnect_translator_btn, 0, 2, 1, 3)
        self.reverse_x_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.reverse_x_btn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reverse_x_btn.sizePolicy().hasHeightForWidth())
        self.reverse_x_btn.setSizePolicy(sizePolicy)
        self.reverse_x_btn.setObjectName("reverse_x_btn")
        self.gridLayout.addWidget(self.reverse_x_btn, 1, 0, 1, 1)
        self.xy_change_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.xy_change_btn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xy_change_btn.sizePolicy().hasHeightForWidth())
        self.xy_change_btn.setSizePolicy(sizePolicy)
        self.xy_change_btn.setObjectName("xy_change_btn")
        self.gridLayout.addWidget(self.xy_change_btn, 1, 1, 1, 2)
        self.reverse_y_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.reverse_y_btn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reverse_y_btn.sizePolicy().hasHeightForWidth())
        self.reverse_y_btn.setSizePolicy(sizePolicy)
        self.reverse_y_btn.setObjectName("reverse_y_btn")
        self.gridLayout.addWidget(self.reverse_y_btn, 1, 3, 1, 2)
        self.shift_x_line = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shift_x_line.sizePolicy().hasHeightForWidth())
        self.shift_x_line.setSizePolicy(sizePolicy)
        self.shift_x_line.setObjectName("shift_x_line")
        self.gridLayout.addWidget(self.shift_x_line, 2, 0, 1, 1)
        self.move_x_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.move_x_btn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.move_x_btn.sizePolicy().hasHeightForWidth())
        self.move_x_btn.setSizePolicy(sizePolicy)
        self.move_x_btn.setObjectName("move_x_btn")
        self.gridLayout.addWidget(self.move_x_btn, 2, 1, 1, 1)
        self.shift_y_line = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shift_y_line.sizePolicy().hasHeightForWidth())
        self.shift_y_line.setSizePolicy(sizePolicy)
        self.shift_y_line.setObjectName("shift_y_line")
        self.gridLayout.addWidget(self.shift_y_line, 2, 2, 1, 2)
        self.move_y_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.move_y_btn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.move_y_btn.sizePolicy().hasHeightForWidth())
        self.move_y_btn.setSizePolicy(sizePolicy)
        self.move_y_btn.setObjectName("move_y_btn")
        self.gridLayout.addWidget(self.move_y_btn, 2, 4, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.disconnect_powermeter_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.disconnect_powermeter_btn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.disconnect_powermeter_btn.sizePolicy().hasHeightForWidth())
        self.disconnect_powermeter_btn.setSizePolicy(sizePolicy)
        self.disconnect_powermeter_btn.setMinimumSize(QtCore.QSize(0, 24))
        self.disconnect_powermeter_btn.setStyleSheet("background-color: rgb(255, 205, 205);")
        self.disconnect_powermeter_btn.setObjectName("disconnect_powermeter_btn")
        self.gridLayout_2.addWidget(self.disconnect_powermeter_btn, 0, 1, 1, 1)
        self.step_along_beam = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step_along_beam.sizePolicy().hasHeightForWidth())
        self.step_along_beam.setSizePolicy(sizePolicy)
        self.step_along_beam.setObjectName("step_along_beam")
        self.gridLayout_2.addWidget(self.step_along_beam, 2, 1, 1, 1)
        self.step_along_beam_n = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step_along_beam_n.sizePolicy().hasHeightForWidth())
        self.step_along_beam_n.setSizePolicy(sizePolicy)
        self.step_along_beam_n.setObjectName("step_along_beam_n")
        self.gridLayout_2.addWidget(self.step_along_beam_n, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.step_across_beam = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step_across_beam.sizePolicy().hasHeightForWidth())
        self.step_across_beam.setSizePolicy(sizePolicy)
        self.step_across_beam.setObjectName("step_across_beam")
        self.gridLayout_2.addWidget(self.step_across_beam, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_n_along = QtWidgets.QLabel(self.layoutWidget)
        self.label_n_along.setText("")
        self.label_n_along.setObjectName("label_n_along")
        self.gridLayout_2.addWidget(self.label_n_along, 5, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_n_across = QtWidgets.QLabel(self.layoutWidget)
        self.label_n_across.setText("")
        self.label_n_across.setObjectName("label_n_across")
        self.gridLayout_2.addWidget(self.label_n_across, 5, 0, 1, 1)
        self.step_across_beam_n = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step_across_beam_n.sizePolicy().hasHeightForWidth())
        self.step_across_beam_n.setSizePolicy(sizePolicy)
        self.step_across_beam_n.setObjectName("step_across_beam_n")
        self.gridLayout_2.addWidget(self.step_across_beam_n, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 3, 1, 1, 1)
        self.connect_powermeter_btn = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connect_powermeter_btn.sizePolicy().hasHeightForWidth())
        self.connect_powermeter_btn.setSizePolicy(sizePolicy)
        self.connect_powermeter_btn.setMinimumSize(QtCore.QSize(0, 24))
        self.connect_powermeter_btn.setStyleSheet("background-color: rgb(211, 255, 190);\n"
"\n"
"")
        self.connect_powermeter_btn.setObjectName("connect_powermeter_btn")
        self.gridLayout_2.addWidget(self.connect_powermeter_btn, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 1, 1, 1)
        self.threshold_line = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.threshold_line.sizePolicy().hasHeightForWidth())
        self.threshold_line.setSizePolicy(sizePolicy)
        self.threshold_line.setObjectName("threshold_line")
        self.gridLayout_3.addWidget(self.threshold_line, 2, 0, 1, 1)
        self.diameter_line = QtWidgets.QLineEdit(self.layoutWidget)
        self.diameter_line.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.diameter_line.sizePolicy().hasHeightForWidth())
        self.diameter_line.setSizePolicy(sizePolicy)
        self.diameter_line.setObjectName("diameter_line")
        self.gridLayout_3.addWidget(self.diameter_line, 2, 1, 1, 1)
        self.begin_measurment_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.begin_measurment_btn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.begin_measurment_btn.sizePolicy().hasHeightForWidth())
        self.begin_measurment_btn.setSizePolicy(sizePolicy)
        self.begin_measurment_btn.setObjectName("begin_measurment_btn")
        self.gridLayout_3.addWidget(self.begin_measurment_btn, 0, 0, 1, 1)
        self.interrupt_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.interrupt_btn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.interrupt_btn.sizePolicy().hasHeightForWidth())
        self.interrupt_btn.setSizePolicy(sizePolicy)
        self.interrupt_btn.setObjectName("interrupt_btn")
        self.gridLayout_3.addWidget(self.interrupt_btn, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1314, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Beam Width Meter"))
        self.label_3.setText(_translate("MainWindow", "Путь сохранения"))
        self.connect_translator_btn.setText(_translate("MainWindow", "Подключить подвижку"))
        self.disconnect_translator_btn.setText(_translate("MainWindow", "Отключить подвижку"))
        self.reverse_x_btn.setText(_translate("MainWindow", "Реверс X"))
        self.xy_change_btn.setText(_translate("MainWindow", "X <-> Y"))
        self.reverse_y_btn.setText(_translate("MainWindow", "Реверс Y"))
        self.move_x_btn.setText(_translate("MainWindow", "Move X"))
        self.move_y_btn.setText(_translate("MainWindow", "Move  Y"))
        self.disconnect_powermeter_btn.setText(_translate("MainWindow", "Отключить измеритель"))
        self.label.setText(_translate("MainWindow", "Шаг поперёк пучка, мм"))
        self.label_6.setText(_translate("MainWindow", "Макс. шагов поперёк"))
        self.label_2.setText(_translate("MainWindow", "Шаг вдоль пучка, мм"))
        self.label_7.setText(_translate("MainWindow", "Макс. шагов вдоль"))
        self.connect_powermeter_btn.setText(_translate("MainWindow", "Подключить измеритель"))
        self.label_4.setText(_translate("MainWindow", "Уровень"))
        self.label_5.setText(_translate("MainWindow", "Диаметр"))
        self.begin_measurment_btn.setText(_translate("MainWindow", "Начать измерение"))
        self.interrupt_btn.setText(_translate("MainWindow", "Прервать измерение"))

from pyqtgraph import PlotWidget
